### ISSUE TITLE
l10n: Missing translations in the Nextcloud app store

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/appstore#695] opened 2020-04-29 17:45 UTC
Translations are missing e.g.:

[Forgot password?](https://github.com/nextcloud/appstore/pull/690/files)
[Alphabetically](https://github.com/nextcloud/appstore/pull/687/files)
[Search in %(category)s
Search in featured apps
Search in all apps](https://github.com/nextcloud/appstore/pull/689/files)

**Comment by mario** [comment] 2020-04-29 22:21
Sorry, but where exactly are they missing?

**Comment by Valdnet** [comment] 2020-04-30 07:20
@mario Below are screenshots from the apps store:

- Search in %(category)s
- Search in featured apps
- Search in all apps

![obraz](https://user-images.githubusercontent.com/47037905/80681676-6d94a200-8ac1-11ea-94f8-79a40f54a30f.png)

- Alphabetically

![obraz](https://user-images.githubusercontent.com/47037905/80681795-a9c80280-8ac1-11ea-8ec2-fc98e1c97a0a.png)

- Forgot password?

![obraz](https://user-images.githubusercontent.com/47037905/80681710-82713580-8ac1-11ea-82ac-eefbfd8fd3bb.png)

And many other improved translations from [updated from transifex ](https://github.com/nextcloud/appstore/commit/75f2f77730acb4c46299df335bb2cb116f1c0cbf), which are not included. The site still has incorrect translations.

**Comment by mario** [comment] 2020-04-30 09:40
@MorrisJobke you know more about transifex/translations than I do - any idea about this?

**Comment by MorrisJobke** [comment] 2020-04-30 10:22
> @MorrisJobke you know more about transifex/translations than I do - any idea about this?

This seems to be an issue with the strings in the Django code itself. They are present in the .po files.

**Comment by bigcat88** [comment] 2023-08-21 11:25
closed as completed, cannot reproduce it on last version. if you see something like this - feel free to create a new issue.

**Closed by bigcat88** 2023-08-21 11:25 UTC
Labels: bug, fixed
