### ISSUE TITLE
500 Error unable to register/login/forgot password

### ISSUE THREAD

**Issue by antitoine** [nextcloud/appstore#711] opened 2020-05-09 07:49 UTC
## Details

* Browser and browser version: Firefox 76.0

## JavaScript Console Output

No console output.

## Steps to reproduce

1. Register a new account with a correct email, with Google Recaptcha checked, a username (with only lower and upper case), a first and last name (with only lower and upper cases), and a password of 18 characters (with lower and upper case, number and special characters).
2. Received a 500 error at this point
3. Try to login or forgot the password also results with a 500 error

**Comment by mario** [comment] 2020-05-09 07:58
Do we have sentry logs @MorrisJobke ?

**Comment by MorrisJobke** [comment] 2020-05-12 07:44
Looks like this one:

```
Internal Server Error: /password/reset/
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/account/views.py", line 104, in post
    response = self.form_valid(form)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/account/views.py", line 645, in form_valid
    form.save(self.request)
  File "/opt/appstore/nextcloudappstore/user/forms.py", line 126, in save
    context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/allauth/account/adapter.py", line 137, in send_mail
    msg.send()
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.5/smtplib.py", line 729, in login
    raise last_exception
  File "/usr/lib/python3.5/smtplib.py", line 720, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.5/smtplib.py", line 641, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: UGFzc3dvcmQ6')
```

**Comment by MorrisJobke** [comment] 2020-05-12 07:46
I found the issue and will check how to fix it.

**Comment by blizzz** [comment] 2020-05-12 11:24
The issue is fixed now, thank you for reporting.

**Closed by blizzz** 2020-05-12 11:24 UTC
