### ISSUE TITLE
App store: Outdated screenshot

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/appstore#610] opened 2019-04-27 20:29 UTC
### Steps to reproduce
1. Open app store
2. Go to category Organization
3. Look for bookmarks app
4. Compare screenshot with up-to-date one https://apps.nextcloud.com/apps/bookmarks

### Expected behaviour
The new screenshot should be displayed.

### Actual behaviour
An old screenshot is being displayed.

### Server configuration

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**Docker

**Comment by juliushaertl** [comment] 2019-06-13 16:00
Maybe @blizzz can check if the sync cronjob has issues? https://github.com/nextcloud/usercontent.apps.nextcloud.com/blob/master/sync.php

**Comment by blizzz** [comment] 2019-06-18 09:18
@marcelklehr it's the correct one now, right? I think this was fixed with a recent maintenance job on that system.

**Comment by marcelklehr** [comment] 2019-06-19 10:05
@blizzz mmh, nope :/ Compare the above URLs, they're still differing.

**Comment by blizzz** [comment] 2019-06-19 22:28
@marcelklehr Hm, i don't have the old screenshot appearing. Perhaps it is somehow stuck in cash? Does cleaning it/a hard reload/trying with a different browser show the expected one?

**Comment by marcelklehr** [comment] 2019-06-20 14:20
I tried with chrome, chromium, firefox and curl. All spit out a screenshot with the old UI.

**Comment by blizzz** [comment] 2019-06-20 20:04
Baffling :-/

**Comment by mario** [comment] 2020-04-29 12:23
Works for me. So closing until we have a way to reproduce.

**Closed by mario** 2020-04-29 12:23 UTC

**Comment by marcelklehr** [comment] 2020-04-29 12:46
Yep, it seems to be fixed now.

**Comment by mario** [comment] 2020-04-29 13:14
Awesome.
