### ISSUE TITLE
Can't create new account, recatcha not shown

### ISSUE THREAD

**Issue by schiessle** [nextcloud/appstore#854] opened 2021-07-01 21:51 UTC
Tried with both Firefox and Chromium and made sure that no add-blocker is activated.

Account creation doesn't show the recaptcha:

![image](https://user-images.githubusercontent.com/1589737/124193303-e2e57380-dac6-11eb-872d-a0e0c9a141ec.png)

On hover it says "The content is blocked. Contact the site owner to fix the issue"

Browser console says:

````
Refused to frame 'https://google.com/' because it violates the following Content Security Policy directive: "frame-src https://www.google.com/recaptcha/".
````

@LukasReschke any idea... I saw that you fixed similar issues in the past?
@blizzz in case some sysadmin work is needed.

**Comment by blizzz** [comment] 2021-07-02 09:38
Duplicate of https://github.com/nextcloud/appstore/issues/833

**Closed by blizzz** 2021-07-02 09:38 UTC
