### ISSUE TITLE
Provide link to "What's new" before upgrading an app...

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/appstore#607] opened 2019-05-13 13:30 UTC
... like Wordpress is doing

![57349368-2566cc00-715a-11e9-96c9-8e906d301dcf](https://user-images.githubusercontent.com/24833757/57625269-d1157f00-7593-11e9-8503-7755820c610a.png)

And provide a link to the app in the app store as well

**Comment by BernhardPosselt** [comment] 2019-05-13 15:52
See https://github.com/nextcloud/appstore/pull/580

**Comment by BernhardPosselt** [comment] 2019-12-13 11:16
Closing this as a duplicate of #580 and most of the parts need to be implemented in the server code, not the app store.

**Closed by BernhardPosselt** 2019-12-13 11:16 UTC
