### ISSUE TITLE
API service is down (http code 503)

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [nextcloud/appstore#632] opened 2019-12-18 21:53 UTC
# Details

* Browser and browser version: Firefox 71.0

## JavaScript Console Output

![Screenshot_20191218_224829](https://user-images.githubusercontent.com/17473656/71126119-a43fdf00-21e8-11ea-8687-ff8a2d3a33b8.png)

![Screenshot_20191218_225228](https://user-images.githubusercontent.com/17473656/71126327-17495580-21e9-11ea-9d51-11b1c0171997.png)

## Steps to reproduce

1. Login to apps.nextcloud.com
2. App developer -> Upload new Release
3. Enter link to tar.gz and Signature
4. Click on "Upload"

## Assumption
The API service is down.

**Comment by PanCakeConnaisseur** [comment] 2019-12-20 14:03
I was able to complete an upload now. Maybe a monitoring of the app service API might lead to a faster problem resolution. I don't know if one exists.

**Comment by BernhardPosselt** [comment] 2019-12-20 14:06
There is monitoring (NewRelic) but I'm unsure if this includes the
reverse proxy/cache and if people actually look at the results.

**Comment by tacruc** [comment] 2020-01-22 13:13
![image](https://user-images.githubusercontent.com/402891/72897060-522b3580-3d21-11ea-813e-0c1a3881f56e.png)

**Comment by mario** [comment] 2020-02-06 13:41
@tacruc looks fine now?

**Comment by jurgenhaas** [comment] 2020-03-18 07:53
Well, I'm seeing 503 response code for the last couple of days every now and then, something like 9 out of 10 times when calling https://apps.nextcloud.com/api/v1/platform/18.0.2/apps.json

**Comment by afterlogic-support** [comment] 2020-03-18 13:43
The issue is still there, it's either 503 (Service Unavailable) or every other time 504 (Gateway Time-out)

**Comment by mario** [comment] 2020-03-30 16:00
This should be fine now so closing for now.

**Closed by mario** 2020-03-30 16:00 UTC

**Comment by PanCakeConnaisseur** [comment] 2020-03-31 16:25
> This should be fine now so closing for now.

What changes were made that lead to this issue being closed now?
