### ISSUE TITLE
Change Github access_token query parameter to Authorization HTTP header

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/appstore#710] opened 2020-05-06 12:17 UTC
We got from Github a message, that we are still using the old way and we should move over to the new one: 

> Hello there!
>
> On May 6th, 2020 at 11:44 (UTC) your application (Nextcloud Appstore) used an access token (with the User-Agent python-requests/2.23.0) as part of a query parameter to access an endpoint through the GitHub API.
>
> https://api.github.com/user
>
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
>
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis.
>
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
>
> Thanks,
> The GitHub Team

@Mario Mind to change this, as you are have worked on the code lately.

**Comment by mario** [comment] 2020-05-06 12:25
Duplicate of https://github.com/nextcloud/appstore/issues/653 :)

**Closed by mario** 2020-05-06 12:25 UTC
