### ISSUE TITLE
manage.py syncnextcloudreleases failes with ModuleNotFoundError

### ISSUE THREAD

**Issue by blizzz** [nextcloud/appstore#981] opened 2023-02-14 11:34 UTC
```
# venv/bin/python manage.py syncnextcloudreleases --oldest-supported="24.0.9"
Traceback (most recent call last):
  File "/opt/appstore/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
```

**Comment by bigcat88** [comment] 2023-05-12 09:24
was the problem solved at the end?

if it is for production then it can be solved with different ways:
from activated venv inside project's root:
```
poetry install
```
or
```
pip install .
```
or
```
poetry export -f requirements.txt --without-hashes > requirements.txt
pip install -r requirements.txt
```

**Comment by bigcat88** [comment] 2023-05-17 22:26
I'll close this, as this is a duplicate of #984

**Closed by bigcat88** 2023-05-17 22:26 UTC
Labels: bug, waiting OP action
