### ISSUE TITLE
Change language code from fi_FI to fi

### ISSUE THREAD

**Issue by perohen** [nextcloud/appstore#479] opened 2017-04-29 15:05 UTC
Nextcloud App Store has a Finnish (Finland) translation https://github.com/nextcloud/appstore/blob/master/locale/fi_FI/LC_MESSAGES/django.po and it also has a generic Finnish translation: https://github.com/nextcloud/appstore/blob/master/locale/fi/LC_MESSAGES/django.po

I think it is unnecessary that there are two different Finnish languages (Transifex only has one Finnish language team). I would suggest that the Finnish (Finland) translation would be deleted and translations from Transifex would be updated to fi/LC_MESSAGES/django.po file. Could that be possible?

For reference also see the same issue with server that was already fixed:
https://github.com/nextcloud/server/issues/869
https://github.com/nextcloud/server/pull/1377

**Comment by BernhardPosselt** [comment] 2017-04-29 21:32
@MorrisJobke please

**Comment by MorrisJobke** [comment] 2017-04-29 22:11
> @MorrisJobke please

Where does the fi comes from, @BernhardPosselt ?

**Comment by MorrisJobke** [comment] 2017-04-29 22:12
Weird stuff ... also some other languages have uncommon names and duplicated entries...

**Comment by BernhardPosselt** [comment] 2017-04-29 22:19
hm could be that you simply have to delete the folder in locales/

**Comment by MorrisJobke** [comment] 2017-04-29 22:20
I will do this as a first step and will see ;)

**Comment by perohen** [comment] 2017-04-30 10:56
Is the translation now added to https://github.com/nextcloud/appstore/blob/master/locale/fi/LC_MESSAGES/django.po file? It seems empty now.

**Comment by BernhardPosselt** [comment] 2017-04-30 11:55
that depends on what is being filled in on transifex

**Comment by perohen** [comment] 2017-04-30 12:04
In Transifex 212 of 266 entries are translated and those were synchronized to fi_FI file, but not to fi file.

**Comment by BernhardPosselt** [comment] 2017-04-30 12:05
oh, so its the reverse :D?

Get rid of fi and use fi_FI?

**Comment by perohen** [comment] 2017-04-30 12:10
That's the problem. Those translation should be synchronized to fi file and fi_FI file should not exist, because we don't have many different versions of Finnish language unlike English (en_US, en_GB, ...) or Spanish (es_ES, es_MX, ...).

**Comment by BernhardPosselt** [comment] 2017-04-30 12:11
Ok, then @MorrisJobke should probably handle it :)

**Comment by BernhardPosselt** [comment] 2017-04-30 12:11
I'll revert the commit

**Comment by BernhardPosselt** [comment] 2017-05-14 10:50
@MorrisJobke ideas? Should we just move the translated po file from fi_FI to fi? Will that work for transifex?

**Comment by MorrisJobke** [comment] 2017-05-16 21:51
> @MorrisJobke ideas? Should we just move the translated po file from fi_FI to fi? Will that work for transifex?

In transifex we only have one and I don't know where the seconds one comes from 😕 And currently I have no time to debug this.

**Comment by MorrisJobke** [comment] 2017-05-16 21:52
Keep it assigned to me and I will have a look later™ on it. ETA within a month

**Comment by BernhardPosselt** [comment] 2017-07-29 08:49
@MorrisJobke bumping this :)

**Comment by rakekniven** [comment] 2018-02-21 10:24
IMHO the existing translation work of fi_FI should be added to fi after changing names. I can do that easily. Just tell me before names are switched.

**Comment by MorrisJobke** [comment] 2018-02-27 13:51
> IMHO the existing translation work of fi_FI should be added to fi after changing names. I can do that easily. Just tell me before names are switched.

The problem is, that we then need to move all translations of all projects to fi. As of now we just map it in our transifex config:

https://github.com/nextcloud/activity/blob/7e09326d3c3511ed10af11828c1ada4f2ca707ab/.tx/config#L3

Maybe we should do this here as well:

https://github.com/nextcloud/appstore/blob/master/.tx/config#L1-L8

**Closed** 2019-08-14 11:47 UTC
Labels: enhancement, medium priority
