### ISSUE TITLE
Translation issue app generator

### ISSUE THREAD

**Issue by DaphneMuller** [nextcloud/appstore#1093] opened 2023-07-27 16:15 UTC
The app store gets translated with Transifex. The app generator form at https://apps.nextcloud.com/developer/apps/generate seems to have the wrong Label for the E-Mail field when the language is in German. Instead of "E-Mail" it says "Benötigt keine Übersetzung. Für den Appstore wird nur die formelle Übersetzung verwendet (de_DE)." (Does not need any translation. For the app store we only uze the formal translation." At first sight, it looks like some kind of Language-Key issue.

**Comment by bigcat88** [comment] 2023-07-27 17:28
This is probably related to https://github.com/nextcloud/appstore/issues/1065

I can't repeat this locally with last version, waiting for appstore deploy, to check if it is present in last version.

**Comment by DaphneMuller** [comment] 2023-07-28 08:45
thank you :)

**Comment by bigcat88** [comment] 2023-08-18 16:23
probably this should be fixed too, need confirmation

**Comment by DaphneMuller** [comment] 2023-08-25 08:41
asked Stephan for confirmation

**Comment by bigcat88** [comment] 2023-11-08 14:52
If the issue is not fixed, please create a new or post here and we will reopen it.

**Closed by bigcat88** 2023-11-08 14:52 UTC
Labels: fixed
